name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    env:
      Project_Name: SysBot.Pokemon.WinForms/SysBot.Pokemon.WinForms.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      - name: Restore dependencies
        run: dotnet restore ${{ env.Project_Name }} --runtime win-x86
      - name: Build
        run: dotnet build ${{ env.Project_Name }} --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ${{ env.Project_Name }} --configuration Release --output ./publish /p:PublishSingleFile=true /p:SelfContained=false /p:RuntimeIdentifier=win-x86
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MergeBot
          path: ./publish

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        run: |
          CURRENT_VERSION=$(grep 'public const string Version' SysBot.Pokemon/Helpers/TradeBot.cs | sed 's/.*Version = "\(.*\)";/\1/')
          echo "Current version is $CURRENT_VERSION"

      - name: Get last version
        id: last_version
        run: |
          LAST_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MergeBot
          path: ./publish

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          files: |
            ./publish/* 